### ISSUE TITLE
Little Brother

### ISSUE THREAD

**Issue by linux-team-france** [lulz3xploit/LittleBrother#1]
Bonjour je voulais vous poser une question.
est il possible d'avoir plusieurs versions de Little Brother, car j'ai la toute première et la nouvelle.
La première ne fonctionne plus.
Mais pour la dernière aucun problème.
PS: il y a un script que j'aime bien dans la première qui n'est pas dans la seconde ( le script pour avoir les numéros de téléphone des personnes.
Merci d'avoir pris le temps de lire mon message.

Linux Team France 
[ linux.team.france@gmail.com ]

**Comment by lulz3xploit** [comment]
Bonjour, je vais essayer d’y remédier je vous tien ou courant une fois la mise à jour faite. Merci de votre soutien.
