### ISSUE TITLE
Use str.join(container) instead of doing it in a dirty way

### ISSUE THREAD

**Issue by ghost** [lulz3xploit/LittleBrother#16]
https://github.com/lulz3xploit/LittleBrother/blob/84b53807838fb73dc20c3fa15fb4da2a7c4f0fe0/core/mailToIP.py#L22

could be rewrite in:

```python
return ', '.join([values[v] for v in ('country', 'region', 'city')])
```

**Comment by lulz3xploit** [comment]
thank you, this has been updated: [source](https://github.com/lulz3xploit/LittleBrother/commit/87a47fc6771f6b03dfe3ef82a88ed3f737d7b70e)
