### ISSUE TITLE
#python3 LittleBrother.py Traceback (most recent call last):   File "LittleBrother.py", line 6, in <module>     from lib.menu import checkVersion, clear, menu   File "/home/ashu/LittleBrother/lib/menu.py", line 2, in <module>     from core.Profiler import *   File "/home/ashu/LittleBrother/core/Profiler.py", line 2, in <module>     from terminaltables import SingleTable ModuleNotFoundError: No module named 'terminaltables'

### ISSUE THREAD

**Issue by ashukalbhor** [lulz3xploit/LittleBrother#17]
#python3 LittleBrother.py
Traceback (most recent call last):
  File "LittleBrother.py", line 6, in <module>
    from lib.menu import checkVersion, clear, menu
  File "/home/ashu/LittleBrother/lib/menu.py", line 2, in <module>
    from core.Profiler import *
  File "/home/ashu/LittleBrother/core/Profiler.py", line 2, in <module>
    from terminaltables import SingleTable
ModuleNotFoundError: No module named 'terminaltables'

**Comment by lulz3xploit** [comment]
you do not have the module terminaletables

Just look the README.md for see the installation. 

For fix your problem: 

Step 1) python3 -m pip install -r requirements.txt 

Step 2) python3 LittleBrother.py

Step 3) Enjoy
