### ISSUE TITLE
Problem with Instagram?

### ISSUE THREAD

**Issue by DocKali** [lulz3xploit/LittleBrother#19]
Hi,

I just discovered your tool and i'm currently trying it. I've always the same issue when searching on a person, here is the traceback I have : 

```
Traceback (most recent call last):
  File "LittleBrother.py", line 199, in <module>
    searchPersonne(settings.codemonpays)
  File "/opt/LittleBrother/core/searchPersonne.py", line 153, in searchPersonne
    instatls.searchInsta(nom)
  File "/opt/LittleBrother/core/instagramSearchTool.py", line 183, in searchInsta
    account = re.findall(r"instagram\.com/(.*?)/", url)[0]
IndexError: list index out of range
```
Any idea from where the error come? 

Thanks for your help!

**Comment by lulz3xploit** [comment]
hello, this problem is normal, it will be corrected in not long, still sorry for this error

**Comment by DocKali** [comment]
OK, thank you for your quick answer! I'll be waiting for the git pull :)

**Comment by lulz3xploit** [comment]
the code is corrected... normally, if the error persists, tell me, and come on the discord that you will find in the README.md

**Comment by DocKali** [comment]
Excellent, it works without problem!
Thanks for your help!

**Comment by bhaijaan2** [comment]
hi i am enable to find the details with instagram or twitter or also enable to serch with the mobile number
kindly guide me
