### ISSUE TITLE
ne marche pas

### ISSUE THREAD

**Issue by eLGROSKompadre** [lulz3xploit/LittleBrother#2]
Bonjour, j'ai un problème, la tool ne se lance pas:

Traceback (most recent call last):                
  File "LittleBrother.py", line 45, in <module>
    from terminaltables import SingleTable, AsciiTable
ModuleNotFoundError: No module named 'terminaltables'

est-ce normal ?  que puis-je faire pour remedier à ça svp ? merci.

**Comment by rolde** [comment]
Il te manque des modules D:

**Comment by KNG6** [comment]
Tiens l'ami il te manque ça:
https://pypi.org/project/terminaltables/
