### ISSUE TITLE
'searchLinkedIn' object has no attribute 'profiles'

### ISSUE THREAD

**Issue by EinderJam** [lulz3xploit/LittleBrother#21]
Le dernier commit supprime toute trace de l'attribut "profiles" de la classe **searchLinkedIn**, ce qui a pour conséquence le crash de LittleBrother (en faisant un "Personne lookup" par exemple"). Je ne sais pas si c'est voulu/si d'autres commits sont en chemin...
Voilà le message d'erreur en eniter :
![image](https://user-images.githubusercontent.com/16850696/60663160-bb6b5a00-9e5e-11e9-973d-3cbb75a8c0a0.png)

**Comment by lulz3xploit** [comment]
Bonjour, j’ai sûrement oublié quelque chose lors de la dernière mise à jour, le code sera corrigé demain, si le problème n’est pas méchant. Merci pour votre issu

**Comment by EinderJam** [comment]
De rien, merci à vous pour votre réponse rapide ^^

**Comment by lulz3xploit** [comment]
le bug a été corrigé ! tu peux télécharger la nouvelle version. Si le bug persiste chez toi ou si tu en trouve d'autre, n'hésite pas à me contacter ici ou sur mon Discord (Lien dans le README.md)
