### ISSUE TITLE
Décalage entre colonnes Name et User

### ISSUE THREAD

**Issue by DocKali** [lulz3xploit/LittleBrother#22]
Bonjour,

J'ai l'impression que dans le listing des comptes Facebook (j'ai pas vérifié pour le reste), l'outil n'associe pas les bons Name aux User. Il y aurait un décalage d'une ligne.
Si je ne suis pas assez clair, je peux envoyer par Telegram ou en mp le nom à partir duquel j'ai pu constater le décalage.

**Comment by sundowndev** [comment]
Pareil sur les pages blanches, si une personne a 2 numéros ça décale toute la liste.

**Comment by lulz3xploit** [comment]
Bonjour. Je prend compte de vos problème. Une mise à jour sera faite prochainement. Mais je ne pourrais pas vous dire quand.

**Comment by lulz3xploit** [comment]
Il me faudrait juste les arguments qui peut poser se problème. Pour pouvoir ensuite debugger.

**Comment by DocKali** [comment]
Bonjour et merci pour ton retour rapide @lulz3xploit 
Pour ma part, j'ai constaté le problème en sélectionnant [1] Lookup / [1] Personne Lookup
En cas de besoin je peux envoyer par message privé les nom, prénom et ville qui m'ont fait constater le problème.
Merci d'avance!!

**Comment by lulz3xploit** [comment]
@DocKali J'aimerais bien avoir ses informations pour pouvoir débug plus facilement le code. Si cela ne vous dérange pas.

**Comment by DocKali** [comment]
Pas de soucis, je vous les adresse comment?

**Comment by lulz3xploit** [comment]
@DocKali Venez sur le serveur discord, https://discord.gg/r8GvsYM. Envoyez un message dans #général et je vous contacterais par message privée
