### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by adi1090x** [lulz3xploit/LittleBrother#25]
Can you please Translate your tool to English?

**Comment by lulz3xploit** [comment]
Yes, but in a new version of LittleBrother

**Comment by adi1090x** [comment]
> Yes, but in a new version of LittleBrother

When are you gonna do that?

**Comment by lulz3xploit** [comment]
no specific date, Little Brother will be improved from A to Z, so it takes time

**Comment by adi1090x** [comment]
> no specific date, Little Brother will be improved from A to Z, so it takes time

Alright, I'll wait for it... Awesome Work!
