### ISSUE TITLE
issues with the links

### ISSUE THREAD

**Issue by awsome-in** [lulz3xploit/LittleBrother#27]
Hi There,
its really awesome experience to use the tool,
but while opening the link we get a error on the page which says **Bad Request along with blank white background. ** this causes unable to look on the photos on facebook or instagram, thanks for making this great tool,  here are some screenshots which may indicate about the issue to understand better :-

![Screen Shot 2020-01-02 at 8 03 26 PM](https://user-images.githubusercontent.com/59444416/71672113-11cc3d80-2d9b-11ea-83b0-49999de468b5.png)
![Screen Shot 2020-01-02 at 8 02 50 PM](https://user-images.githubusercontent.com/59444416/71672123-17c21e80-2d9b-11ea-8e82-218074c56660.png)

**Comment by lulz3xploit** [comment]
hello i will find a solution to fix this

**Comment by lulz3xploit** [comment]
@awsome-in The bug has been fixed.
