### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by ghost** [lulz3xploit/LittleBrother#3]
https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L127

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L129

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L136

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L138

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L235

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L398

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L468

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L537

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L539

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L548

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L1376

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L1456

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L1460

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L1564

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L1574

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L1910

Also some weird stuffs:

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L571

https://github.com/lulz3xploit/LittleBrother/blob/e59d8f5b2b73ae17cd7af7addc12aee5d9ca9fe3/LittleBrother.py#L1466

**Comment by ghost** [comment]
Why closing this issue? It has not been fixed yet

**Comment by lulz3xploit** [comment]
because this has been corrected

**Comment by ghost** [comment]
That's not true:

https://github.com/lulz3xploit/LittleBrother/blob/84b53807838fb73dc20c3fa15fb4da2a7c4f0fe0/core/mailToIP.py#L15

https://github.com/lulz3xploit/LittleBrother/blob/84b53807838fb73dc20c3fa15fb4da2a7c4f0fe0/core/mailToIP.py#L22

**Comment by lulz3xploit** [comment]
thank you for improving the code and supporting little brother but your changes are not vital for this one

**Comment by lrhel** [comment]
Hey, 
Thank you for your feedback.
We know the code is inconsistent, we are working on it, slowly but surely
