### ISSUE TITLE
problem with the argument 

### ISSUE THREAD

**Issue by backl1n** [lulz3xploit/LittleBrother#36]
Traceback (most recent call last):
  File "LittleBrother.py", line 223, in <module>
    searchInstagram()
  File "/home/kali/Documents/LittleBrother/core/searchInstagram.py", line 21, in searchInstagram
    images = shortCutUrl(images)
  File "/home/kali/Documents/LittleBrother/core/shortCutUrl.py", line 6, in shortCutUrl
    url = Url(url).decode()
  File "/home/kali/Documents/LittleBrother/lib/Url.py", line 47, in decode
    while '%' in url:
TypeError: argument of type 'NoneType' is not iterable

**Comment by lulz3xploit** [comment]
@raxou can you give me the item used when you encountered this error?

**Comment by backl1n** [comment]
Instagram research

**Comment by backl1n** [comment]
M'y Friends use and they find 0 bug

**Comment by backl1n** [comment]
Instagram research and twitter research sorry

**Comment by lulz3xploit** [comment]
@raxou can you give me the nickname used?  come on the discord I will come to see you in a private message https://discord.gg/r8GvsYM

**Comment by backl1n** [comment]
The link is false

**Comment by backl1n** [comment]
My discord  BackL1n#7060

**Comment by lulz3xploit** [comment]
@raxou Your link is false to :( join here : https://discord.gg/vK4unk

**Comment by backl1n** [comment]
The link is Idem

**Comment by backl1n** [comment]
Add me on discord

**Comment by lulz3xploit** [comment]
I send

**Comment by backl1n** [comment]
Give me your name on the discord i doesnt receive

**Comment by backl1n** [comment]
Five me your name on the discord i doesnt receive

**Comment by backl1n** [comment]
> I send 

I doesnt receive your invitation give me your pseudo
