### ISSUE TITLE
RIP MA VIE

### ISSUE THREAD

**Issue by G33K01D-C137-zz** [lulz3xploit/LittleBrother#4]
Traceback (most recent call last):
  File "littlebrother.py", line 6, in <module>
    from colorama import init, Fore,  Back,  Style
ModuleNotFoundError: No module named 'colorama'

J'ai essayer plein de truc ça marche pas .... HELP !!!

**Comment by lulz3xploit** [comment]
Salut, il faut que tu installe la librairie colorama.

Linux/Windows: pip3 install colorama

Si tu n’a pas pip, Je te laisse chercher comment l’installer.

**Comment by G33K01D-C137-zz** [comment]
ok merci !

**Comment by G33K01D-C137-zz** [comment]
AAHHHHHHHHHHH ! En plus j'arrive pas a l'import ni a le pip install...

 ` File "LittleBrother.py", line 118, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'
`

**Comment by lulz3xploit** [comment]
Malheureusement pour se module il faut le télécharger sur le site : http://www.dnspython.org

Tu lance le setup.py avec python3 

Python3 setup.py install

**Comment by G33K01D-C137-zz** [comment]
Merci de cette réponse ( très ) rapide *thumbsup*
