### ISSUE TITLE
Problem with the Person Lookup

### ISSUE THREAD

**Issue by Niphasio** [lulz3xploit/LittleBrother#40]
When I try to do some research on myself on on anyone else (with their agree) this message appear.
I tried to search the problem  compare the sourcecode of my files and the sourcecode on your Github, but nothing differents 

here's the message : 

3Traceback (most recent call last):
  File "LittleBrother.py", line 199, in <module>
    searchPersonne(settings.codemonpays)
  File "/root/LittleBrother/core/searchPersonne.py", line 43, in searchPersonne
    searchPJ(requete)
  File "/root/LittleBrother/core/searchPJ.py", line 39, in searchPJ
    p.search(n)
  File "/root/LittleBrother/core/searchInfoNumero.py", line 37, in search
    ville = p[3]
IndexError: list index out of range
root@kali:~/LittleBrother# 3

thx for ur answser and ur help ;)

**Comment by lulz3xploit** [comment]
Hello @Niphasio, visibly an update was made on the site. I need to update the code. If it’s not too complicated, I’d do it fast enough.

**Comment by lulz3xploit** [comment]
@Niphasio This has been corrected! You can download the new version of LittleBrother now. Thank you for warning me of this problem.

**Comment by Niphasio** [comment]
@lulz3xploit ur welcome, just, where can I download the update ? ^^'

**Comment by Niphasio** [comment]
i already fine, sorry for the mention

**Comment by lulz3xploit** [comment]
@Niphasio If you are on Linux and have downloaded Littlebrother with the "git" tool, you can go to the LittleBrother directory and run `git pull` command. Otherwise you can download the new version in the same place or you downloaded littlebrother for the first time :) [here](https://github.com/lulz3xploit/littlebrother), on the github page.

**Comment by Niphasio** [comment]
okay, Btw there is 2 more "problem" , i post them here or i create a  new issue ? @lulz3xploit

**Comment by lulz3xploit** [comment]
@Niphasio If you’ve seen any other problem, look at whether there’s no existing Issue on the subject, otherwise create a new issue please

**Comment by Niphasio** [comment]
no problem i do that right now
