### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Niphasio** [lulz3xploit/LittleBrother#44]
Traceback (most recent call last):
  File "LittleBrother.py", line 199, in <module>
    searchPersonne(settings.codemonpays)
  File "/root/LittleBrother/core/searchPersonne.py", line 43, in searchPersonne
    searchPJ(requete)
  File "/root/LittleBrother/core/searchPJ.py", line 39, in searchPJ
    p.search(n)
  File "/root/LittleBrother/core/searchInfoNumero.py", line 36, in search
    operator = p[3]
IndexError: list index out of range

i think that i will found all the times those error code and report to you XD
btw thank's by advance for your answers :wink:

**Comment by lulz3xploit** [comment]
Hello @Niphasio, I will correct this as soon as possible !

**Comment by lulz3xploit** [comment]
@Niphasio I fixed the problem! You can download the new version of littlebrother now

**Comment by maximedotair** [comment]
Sympa, je peux vous fournir une api si vous préférez, de plus la je peux vous faire scrapper n'importe quoi et faire de l'injection python sur tout ce qui use littlebrother via de l'injection dans un array si je veux, et en random :))

le dev de infos-numero

**Comment by lulz3xploit** [comment]
@kwizfreak Bonjour, je vous ai envoyé un mail
