### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by OPOZ999** [lulz3xploit/LittleBrother#46]
Hi,
I do not understand I can not install the cli on windows. Can somebody help me please

**Comment by lulz3xploit** [comment]
@OPOZ999 The step for installing LittleBrother on windows is here [Windows](https://github.com/lulz3xploit/LittleBrother#Installation-sur-Windows)

**Comment by OPOZ999** [comment]
yes but It does not work

**Comment by OPOZ999** [comment]
![image](https://user-images.githubusercontent.com/74661109/99533321-f7e11c80-29a5-11eb-8598-f7ea52b8d908.png)

**Comment by lulz3xploit** [comment]
Vous avez installé Python depuis le store Windows ou via le site [officiel](https://www.python.org) ?

**Comment by OPOZ999** [comment]
T'es Fr ?
Oui depuis le site et l'app store 
![image](https://user-images.githubusercontent.com/74661109/99533927-ecdabc00-29a6-11eb-9dc3-523818d17873.png)

**Comment by lulz3xploit** [comment]
Bah le readme est en FR donc y'a un indice.. 

et si tu change python3 par python ? 

Et le readme recommande seulement d'installer python via le store Windows, donc si ça fonctionne toujours pas, supprime python de ton Windows, et réinstalle le seulement a partir du store.

**Comment by OPOZ999** [comment]
tu as un lien d'installation de python stp

**Comment by lulz3xploit** [comment]
[python3](https://www.microsoft.com/fr-fr/p/python-37/9nj46sx7x90p)

**Comment by OPOZ999** [comment]
sur le microsoft strore impossible d'installer 
Wllh je capte pas pk

**Comment by OPOZ999** [comment]
J'ai python mais regarde sa marche pas 
![image](https://user-images.githubusercontent.com/74661109/99537261-bbb0ba80-29ab-11eb-9a01-52385350ba9a.png)
![image](https://user-images.githubusercontent.com/74661109/99537315-cb300380-29ab-11eb-8669-902ae00577fc.png)

**Comment by OPOZ999** [comment]
![image](https://user-images.githubusercontent.com/74661109/99537576-25c95f80-29ac-11eb-9c52-7c513ab4f652.png)

**Comment by lulz3xploit** [comment]
Tu a python dans tes variables d'environnement ?

**Comment by ghost** [comment]
> J'ai python mais regarde sa marche pas
> ![image](https://user-images.githubusercontent.com/74661109/99537261-bbb0ba80-29ab-11eb-9a01-52385350ba9a.png)
> ![image](https://user-images.githubusercontent.com/74661109/99537315-cb300380-29ab-11eb-8669-902ae00577fc.png)

Tu as différentes manières d'ajouter Python à tes variables d'environnement, la plus simple pour toi serrai de re-installer Python et de bien cocher "Add python to path" lors de l'installation
