### ISSUE TITLE
Contact for contribution

### ISSUE THREAD

**Issue by ghost** [lulz3xploit/LittleBrother#48]
Hi, I'd like to contribute to your project. But I would get your email adress or discord to talk about it. Waiting for your answer, have a nice day. 
Ps : I'm French

**Comment by lulz3xploit** [comment]
Bonjour, merci pour votre proposition de contribution. Malheureusement je travaillais déjà sur une nouvelle version avec quelqu'un d'autre, version qui ne vera pas le jour car plus rien nous motive à le faire à cause de la mauvaise image que véhicule le projet ainsi que la mauvaise utilisation que fait certains utilisateurs avec cet outil. Mais si tout de même vous voulez corriger des erreurs existantes sur ce projet, un PR sera quand même accepté. Visiblement les modules de recherche instagram et Twitter ne fonctionnent plus et je ne cherche pas à résoudre cela et je ne veux pas que vous les corrigiez, car d'ici 2-3 semaines leurs sites seront encore mis à jour et il faudra encore modifier le code etc etc. Donc ne vous occupez pas de ces modules. Merci encore pour votre proposition, encore désolé de devoir la refuser.

**Comment by ghost** [comment]
> Bonjour, merci pour votre proposition de contribution. Malheureusement je travaillais déjà sur une nouvelle version avec quelqu'un d'autre, version qui ne vera pas le jour car plus rien nous motive à le faire à cause de la mauvaise image que véhicule le projet ainsi que la mauvaise utilisation que fait certains utilisateurs avec cet outil. Mais si tout de même vous voulez corriger des erreurs existantes sur ce projet, un PR sera quand même accepté. Visiblement les modules de recherche instagram et Twitter ne fonctionnent plus et je ne cherche pas à résoudre cela et je ne veux pas que vous les corrigiez, car d'ici 2-3 semaines leurs sites seront encore mis à jour et il faudra encore modifier le code etc etc. Donc ne vous occupez pas de ces modules. Merci encore pour votre proposition, encore désolé de devoir la refuser.

Aucun problème. Merci de votre réponse
