### ISSUE TITLE
Fix for macos 

### ISSUE THREAD

**Issue by ronanlaunay** [lulz3xploit/LittleBrother#5]
Hi, 

I'm using this tool with macOS 10.13.6 (High Sierra). 
For using it, you need to install python3 using brew : 
`brew install python3`
and self-upgrade pip : 
`pip install --upgrade pip`
and install dependencencies :  
`pip3 install requests bs4 terminaltables colorama exifread dnspython`
The python module are terminaltables not terminaletables

Notta Bene : for dependencies fix, the problem are same on other Unix-like OS.  

Despite these elements, the program work great !

**Comment by lulz3xploit** [comment]
hello, I saw the spelling mistake for terminal table, I will correct that with the new update of littlebrother. I do not have a computer under MacOS, so I could not try littlebrother, sorry. thank you again for your support.

**Comment by KNG6** [comment]
Probably `brew install python3-pip ` ?
