### ISSUE TITLE
Auccun respect PEP8, Manque cruel d'optimisation

### ISSUE THREAD

**Issue by barnabehvrd** [lulz3xploit/LittleBrother#54]
Code non-optimisé, manque cruel du respect pep-8

* Certaines lignes sont inutiles (comme :)
```python
if condition:
    fonction()
else:
    pass
``` 
[source](https://github.com/lulz3xploit/LittleBrother/blob/272de822f6708f87a1c1f53a8df6f8c10493426b/core/searchGoogle.py#L60),

-------
 * Des fonctions comportant des majuscules (comme:)
```python
def searchGoogle(requete='', requete2=''):
```
* Dans l'exemple montré plus haut, des strings seront donnés par défaut, il faut donc préciser que des `requests.Reponse` sont attendues

```python
def search_google(requete: request.Reponses = '', requete2: request.Reponses= ''):
```
[pep8](https://pep8.org/#other-recommendations),
[source](https://github.com/lulz3xploit/LittleBrother/blob/272de822f6708f87a1c1f53a8df6f8c10493426b/core/searchGoogle.py#L3),

-----------
* Plusieurs modules importés sur une même ligne
```python
import sys, os, time, random, threading
```
[pep8](https://pep8.org/#imports)

-----

Code spaghetti : 
```py
		if lookup == 'h':
					print(helpLookup)
				elif lookup.lower() == '1':
					searchPersonne(settings.codemonpays)
				elif lookup.lower() == '2':
					searchUserName()
				elif lookup.lower() == '3':
					searchAdresse(settings.codemonpays)
				elif lookup.lower() == '4':
					searchNumber(settings.codemonpays)
#                                 [...]
	
```
Ce code est tout simplement infâme. Il aurait pu être rendu plus agréable avec des dicts :

(petit exemple)
```py
nb =  int(input("Index:"))
# supposont que printa() printb() et printc() sont des fonctions définies antérieurement
choice = {"a": printa, 
             "b": printb,
             "c" printc }
funct  = choice[nb]
funct()
>>> Index: a
>>> "a"
```

-------
* Il n'est pas recommandé d'utiliser `excpect` à tout vas, surtout sans préciser le type d'exception derrière. Il serait dur de détecter un bug pouvant être réglé facilement
[pep8](https://www.flake8rules.com/rules/E722.html)

------

* Des fonctions sont présentes dans d'autres fonctions.
L'utilisation de class est à privilégier
[exemple](https://github.com/lulz3xploit/LittleBrother/blob/272de822f6708f87a1c1f53a8df6f8c10493426b/core/searchPageDor.py#L6)

```py
class main:
    def __init__(self,something)
        self.do_stuff(something)
    def do_stuff(something)
        return something

**Comment by lrhel** [comment]
Bonjour,
Vous êtes libre d'ouvrir un  Pull Request.
Bien à vous
