### ISSUE TITLE
NameError: name 'internet' is not defined

### ISSUE THREAD

**Issue by Frenchcor3** [lulz3xploit/LittleBrother#7]
Salut, L'osque j'exécute LittleBrothers, j'ai se type de problèmes, merci d'avance pour votre réponses 

traceback (most recent call last):
  File "LittleBrother.py", line 1998, in <module>
    menu()
  File "LittleBrother.py", line 1992, in menu
    """ % (Fore.YELLOW+str(today)+Fore.RESET, Fore.YELLOW+times()+Fore.RESET, Fore.YELLOW+str(__version__)+Fore.RESET, internet, random.choice(text))
NameError: name 'internet' is not defined

**Comment by lulz3xploit** [comment]
Salut, cet erreur est très fréquente. C’est à cause d’un module qui n’est pas installé. Ça devrai être dns.python ou exifread. Si le problème persiste dite le moi
