### ISSUE TITLE
ligne 541: today = date.today() 'date' is not defined

### ISSUE THREAD

**Issue by ghost** [lulz3xploit/LittleBrother#8]
salut j'ai ce problème sous linux, avec ta version 5.0 et je sais pas d'ou ça vien t'a une soluce ? et puis y a aussi threading qui merde

**Comment by Frenchcor3** [comment]
pip3 Install exifread

-----Message d'origine-----
De : "quiotto" <notifications@github.com>
Envoyé : ‎08/‎01/‎2019 20:08
À : "lulz3xploit/LittleBrother" <LittleBrother@noreply.github.com>
Cc : "Subscribed" <subscribed@noreply.github.com>
Objet : [lulz3xploit/LittleBrother] ligne 541: today = date.today() 'date' isnot defined (#8)

salut j'ai ce problème sous linux, avec ta version 5.0 et je sais pas d'ou ça vien t'a une soluce ?

**Comment by ghost** [comment]
je l'ai déjà fait et ça n'a pas réglé le problème

**Comment by AzarathME** [comment]
Sous Linux, c'est simple, python n'arrive pas à définir date-today(), puisque tu ne l'as pas installé.
Pour résoudre ce problème : 
**- pip3 install datetime**
Ensuite, tu vas avoir encore la même erreur, ne panique pas c'est qui faut faire un : 
**- pip3 install terminaltables**

Derien, c'était Azarath à votre service !

**Comment by ghost** [comment]
ok cool je vais essayer
